config/routes.rb
Rails.application.routes.draw do
  #Errors
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  get 'users/index'

  #Devise
  devise_for :users, skip: [:sessions]
  as :user do
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
                   via: Devise.mappings[:user].sign_out_via
  end

  get 'home', to: 'home#index'
  get 'search', to: 'users#search'
  get '/users/showfollowing', to: 'users#showfollowing', as: 'showfollowing'
  get '/users/showfollowers', to: 'users#showfollowers', as: 'showfollowers'
  get '/users/follow/:id', to: 'followers#follow', as: 'follow'
  get '/users/unfollow/:id', to: 'followers#unfollow', as: 'unfollow'
  put 'like/:id', to: 'posts#like', as: 'like'

  resources :posts, except: [:show]
  resources :comments, except: [:show]
  resources :users, only: [:update, :show]
  resources :events, except: [:show]

  #Página inicial
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Relationships
  has_many :posts
  has_many :following, :class_name => 'Follower', :foreign_key => 'current_id'

  # User Avatar Validation
  validates :avatar, presence: true
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  # kaminari
  QTT_PER_PAGE = 5

  # scope
  scope :search, -> (q, page) {where("lower(name) LIKE ?", "%#{q.downcase}%"
                    ).page(page).per(QTT_PER_PAGE)}
  scope :filter_all, -> (page) {User.all.page(page).per(QTT_PER_PAGE)}

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @posts = Post.by_user(current_user, params[:page])
    @following = current_user.following.order(:created_at).limit(6)
    @followers = Follower.get_followers(current_user.id).order(:created_at).limit(6)
  end

  def search
    cookies[:search_t] = params[:q]
    if params[:q].blank?
      @users = User.filter_all(params[:page])
    else
      @users = User.search(params[:q], params[:page])
    end
  end

  def show
     @user = User.friendly.find(params[:id])
  end

  def showfollowing
    @following = current_user.following
  end

  def showfollowers
    @followers = Follower.get_followers(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :about, :avatar, :avatar_cache,
                                 :remove_avatar,:q)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="profile">
              <div class="row">

                <div class="pull-left">
                  <h1 class="page-header"><%= @user.name %></h1>
                </div>

                <div class="pull-right">
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default" %>
                </div>

                <div class="clearfix"></div>

              </div>
              <div class="row">
                <div class="col-md-4">
                  <%= image_tag(@user.avatar.url(:medium), alt: @user.name, class: "img-thumbnail") %>
                </div>
                <div class="col-md-8">
                  <ul>
                    <li><strong>Name: </strong><%= @user.name %></li>
                    <li><strong>Email: </strong><%= @user.email %></li>
                    <li><strong>About</strong></li>
                    <li><%= @user.about %></li>
                  </ul>
                </div>
              </div><br><br>
              <div class="row">
                <div class="col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Profile Wall</h3>
                    </div>
                    <div class="panel-body">
                      <% @posts.each do |p| %>
                        <div class="panel panel-default post">
                          <div class="panel-body">
                            <div class="text-left">
                                <%= p.content %>
                            </div>

                            <div class="text-left postedat">
                              <%= time_ago_in_words(p.updated_at) %>
                            </div>
                            <p class="text-left post-actions">
                              <%= link_to "Edit", edit_post_path(p.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
                              <%= link_to "Delete", post_path(p.id), method: :delete, data: {confirm: t('messages.confirm')} %>
                            </p>
                          </div>
                        </div>
                      <% end %>

                      <!-- posts -->
                      <%= paginate @posts %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <%= render partial: "shared/following" %>
          </div>

          <div class="col-md-4">
            <div class="panel panel-default friends">
              <div class="panel-heading">
                <h3 class="panel-title">Followers</h3>
              </div>

              <div class="panel-body">
                <% unless @followers.blank? %>
                <ul>
                  <% @followers.each do |fow| %>
                    <li>
                      <%= link_to user_path(fow.current), class: "thumbnail" do %>
                        <%= image_tag(fow.current.avatar.url(:medium)) %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
                <div class="clearfix"></div>
                <%= link_to "View All", showfollowers_path, class: "btn btn-primary" %>
                <% end %>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>

<div id="edit-modal" class="modal fade" role="dialog"></div>

app/views/users/search.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h1 class="page-header">Showing members</h1>
            <div class="row member-row">
              <% if @users.blank? %>
                <div class="text-center">
                  Sorry, no matches found for <b><%= cookies[:search_t] %></b>
                </div>
            </div>
            <% else %>
              <% @users.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.avatar.url(:medium), alt: u.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                      <% if u.id != current_user.id %>
                        <p>
                          <% if current_user.following.exists?(:follower_id => u.id) %>
                            <%= link_to unfollow_path(current_user.following.where(:follower_id => u.id).ids), class: "btn btn-danger btn-block" do %>
                              <i class="fa fa-users"></i>
                               <span>Unfollow</span>
                            <% end %>
                          <% else %>
                            <%= link_to follow_path(u.id), class: "btn btn-primary btn-block" do %>
                              <i class="fa fa-users"></i>
                               <span>Follow</span>
                            <% end %>
                          <% end %>
                        </p>
                      <% end %>
                  </div>

                  <div class="col-md-3">
                      <% if u.id == current_user.id %>
                        <p>
                          <%= link_to "My Profile", users_index_path, class: "btn btn-primary btn-block"%>
                        </p>
                      <% else %>
                        <p>
                          <%= link_to user_path(u), class: "btn btn-primary btn-block" do %>
                            <i class="fa fa-edit"></i>
                             <span>View Profile</span>
                          <% end %>
                        </p>
                      <% end %>
                  </div>
                </div>
              <% end %>

              <%= paginate @users %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 profile">
          <h3 class="page-header"><%= @user.name %></h3>
            <div class="row">
              <div class="col-md-4">
                <%= image_tag(@user.avatar.url(:medium), alt: @user.name, class: "img-thumbnail") %><br>
                <% if @user.id != current_user.id %>
                  <p>
                    <% if current_user.following.exists?(:follower_id => @user.id) %>
                      <%= link_to unfollow_path(current_user.following.where(:follower_id => @user.id).ids), class: "btn btn-danger btn-block" do %>
                        <i class="fa fa-users"></i>
                         <span>Unfollow</span>
                      <% end %>
                    <% else %>
                      <%= link_to follow_path(@user.id), class: "btn btn-primary btn-block" do %>
                        <i class="fa fa-users"></i>
                         <span>Follow</span>
                      <% end %>
                    <% end %>
                  </p>
                <% end %>
              </div>
              <div class="col-md-8">
                <ul>
                  <li><strong>Email: </strong><%= @user.email %></li>
                  <li><strong>About</strong></li>
                  <li><%= @user.about %></li>
                </ul>
              </div>
            </div>
      </div>
    </div>
  </div>
</section>

app/views/users/showfollowers.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h1 class="page-header">Who is following me?</h1>
            <div class="row member-row">
              <% if @followers.blank? %>
                <div class="text-center">
                  Sorry, you don't follow anyone.
                </div>
            </div>
            <% else %>
              <% @followers.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.current.avatar.url(:medium), alt: u.current.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.current.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                  </div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to user_path(u.current), class: "btn btn-primary btn-block" do %>
                          <i class="fa fa-edit"></i>
                           <span>View Profile</span>
                        <% end %>
                      </p>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/showfollowing.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h1 class="page-header">My following list</h1>
            <div class="row member-row">
              <% if @following.blank? %>
                <div class="text-center">
                  Sorry, no one is following you.
                </div>
            </div>
            <% else %>
              <% @following.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.follower.avatar.url(:medium), alt: u.follower.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.follower.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to unfollow_path(current_user.following.where(:follower_id => u.follower.id).ids), class: "btn btn-danger btn-block" do %>
                          <i class="fa fa-users"></i>
                           <span>Unfollow</span>
                        <% end %>
                      </p>
                  </div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to user_path(u.follower), class: "btn btn-primary btn-block" do %>
                          <i class="fa fa-edit"></i>
                           <span>View Profile</span>
                        <% end %>
                      </p>
                  </div>
                </div>
              <% end %>

            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>