config/routes.rb
Rails.application.routes.draw do
  #Errors
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  get 'users/index'

  #Devise
  devise_for :users, skip: [:sessions]
  as :user do
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
                   via: Devise.mappings[:user].sign_out_via
  end

  get 'home', to: 'home#index'
  get 'search', to: 'users#search'
  get '/users/showfollowing', to: 'users#showfollowing', as: 'showfollowing'
  get '/users/showfollowers', to: 'users#showfollowers', as: 'showfollowers'
  get '/users/follow/:id', to: 'followers#follow', as: 'follow'
  get '/users/unfollow/:id', to: 'followers#unfollow', as: 'unfollow'
  put 'like/:id', to: 'posts#like', as: 'like'

  resources :posts, except: [:show]
  resources :comments, except: [:show]
  resources :users, only: [:update, :show]
  resources :events, except: [:show]

  #Página inicial
  root 'home#index'
end

app/views/shared/_comment.html.erb
<div class="comment-form">
 <%= form_tag comments_path, class: "form-inline" do%>
   <div class="form-group">
     <%= text_field :comment, :content, class:"form-control", placeholder:"Enter a comment" %>
     <%= hidden_field :comment, :post_id, value: p.id %>
     <%= hidden_field :comment, :user_id, value: current_user.id %>
   </div>
   <%= submit_tag "Add", class: "btn btn-default" %>
 <% end %>
</div>

app/views/shared/_following.html.erb
<div class="panel panel-default friends">
  <div class="panel-heading">
    <h3 class="panel-title">Following</h3>
  </div>
  <div class="panel-body">
    <% unless @following.blank? %>
    <ul>
      <% @following.each do |fol| %>
        <li>
          <%= link_to user_path(fol.follower), class: "thumbnail" do %>
            <%= image_tag(fol.follower.avatar.url(:medium)) %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="clearfix"></div>
    <%= link_to "View All", showfollowing_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
      <div class="container">
        <p>Luís Felipe Bilecki, <%= Time.new.year %></p>
      </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="container">
      <% if user_signed_in? %>

          <div class="pull-right">Welcome!, <%= current_user.name %></div><br>
          <div class="pull-right">
            <span class="glyphicon glyphicon-log-out"></span> <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logout" %>
          </div>

      <% else %>

        <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form-inline"}) do |f| %>
            <div class="form-group">
              <%= f.label :email, class: "sr-only" %>
              <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter Email" %>
            </div>

            <div class="form-group">
              <%= f.label :password, class: "sr-only" %>
              <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
            </div>


            <%= f.submit "Sign in", class: "btn btn-default" %>

            <br>

            <div class="checkbox">
              <label>
                <%= f.check_box :remember_me %> Remember me
              </label>
            </div>
        <% end %>

      <% end %>

    </div>

  </header>


<nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>

            <% if user_signed_in? %>
              <li><%= link_to "My Profile", users_index_path %></li>
              <li><%= link_to "Following", showfollowing_path %></li>
              <li><%= link_to "Followers", showfollowers_path %></li>

            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>

          </ul>

          <% if user_signed_in? %>
          <div class="pull-right" style="margin-right:-30px;">

            <%= form_tag search_path, method: :get, class: "navbar-form", role: "search" do %>
              <div class="input-group">
                <%= text_field_tag(:q, params[:q], { class:"form-control", placeholder: "Search..."}) %>

                <span class="input-group-btn">
                  <%= button_tag(:name => nil, type: "submit", class: "btn btn-default") do %>
                     <i class="glyphicon glyphicon-search"></i>
                <% end %>
                </span>

              </div>
            <% end %>

          </div>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/shared/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify({
                            // options
                            message: '#{notice}'
                          },{
                            // settings
                            type: 'success',
                            placement: {from: 'top', align: 'center'}
                          });" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify({
                            // options
                            message: '#{alert}'
                          },{
                            // settings
                            type: 'danger',
                            placement: {from: 'top', align: 'center'}
                          });" %>

<% end %>