config/routes.rb
Rails.application.routes.draw do
  #Errors
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  get 'users/index'

  #Devise
  devise_for :users, skip: [:sessions]
  as :user do
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
                   via: Devise.mappings[:user].sign_out_via
  end

  get 'home', to: 'home#index'
  get 'search', to: 'users#search'
  get '/users/showfollowing', to: 'users#showfollowing', as: 'showfollowing'
  get '/users/showfollowers', to: 'users#showfollowers', as: 'showfollowers'
  get '/users/follow/:id', to: 'followers#follow', as: 'follow'
  get '/users/unfollow/:id', to: 'followers#unfollow', as: 'unfollow'
  put 'like/:id', to: 'posts#like', as: 'like'

  resources :posts, except: [:show]
  resources :comments, except: [:show]
  resources :users, only: [:update, :show]
  resources :events, except: [:show]

  #Página inicial
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def index
    @user = User.new

    unless current_user.blank?
      following_list = current_user.following
      @following =  following_list.order(:created_at).limit(6)

      values =  following_list.pluck(:follower_id)
      @posts = Post.subscribed(values, params[:page])
    end
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <section>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Wall</h3>
          </div>
          <div class="panel-body">
            <%= form_tag posts_path do%>
              <div class="form-group">
                <%= text_area :post, :content, class:"form-control", rows: 3, placeholder:"Write on the wall" %>
                <%= hidden_field :post, :user_id, value: current_user.id %>
              </div>
              <%= submit_tag "Submit", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
        <div class="panel panel-default post">
          <div class="panel-body">
             <% if @posts.blank? %>
              <div class="row">
                <p>You need to follow someone to see posts.</p>
              </div>
             <% else %>
               <% @posts.each do |p| %>
               <div class="row">
                 <div class="col-sm-2">
                    <%= link_to user_path(p.user), class: "post-avatar thumbnail" do %>
                      <%= image_tag(p.user.avatar.url(:thumb), alt: @user.name) %>
                    <% end %>
                    <div class="text-center"><%= p.user.name %></div>
                   <div class="likes text-center">
                     <%= pluralize(p.get_likes.size,"Like") %>
                   </div>
                 </div>
                 <div class="col-sm-10">
                   <div class="bubble">
                     <div class="pointer">
                       <p><%= p.content %></p>

                       <p class="properties">
                        <%= time_ago_in_words(p.updated_at) %>
                       </p>

                     </div>
                     <div class="pointer-border"></div>
                   </div>
                   <p class="post-actions">
                    <%= link_to "Like", like_path(p), method: :put %>
                   </p>
                   <br/>
                   <p style="color: #04519b;">Comments</p>

                   <% if p.comments.blank? %>
                      <%= render partial: "shared/comment", locals: {p: p} %>
                   <% end %>

                   <% p.comments.order(updated_at: :desc).each do |c| %>
                   <div class="comments">
                     <div class="comment">
                      <%= link_to '', class: "comment-avatar pull-left" do %>
                        <%= image_tag(c.user.avatar.url(:thumb)) %>
                      <% end %>

                       <div class="comment-text">
                        <!-- owner -->
                        <div class="pull-left properties">
                         <%= c.user.name %>
                        </div>

                         <!-- owner -->
                         <div class="pull-right properties">
                          <%= time_ago_in_words(c.updated_at) %>
                          <% if c.user == current_user %>
                              <%= link_to comment_path(c.id), method: :delete, data: {confirm: t('messages.confirm')} do %>
                                  <i class="fa fa-close"></i>
                               <% end %>

                              <%= link_to edit_comment_path(c.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'} do %>
                                  <i class="fa fa-pencil"></i>
                               <% end %>

                          <% end %>
                         </div>

                         <div class="clearfix"></div>

                         <p><%= c.content %></p>
                       </div>

                     </div>
                     <div class="clearfix"></div>
                   </div>
                   <% end %>

                   <% unless p.comments.blank? %>
                      <%= render partial: "shared/comment", locals: {p: p} %>
                   <% end %>

                 </div>
               </div>
               <br/>
               <% end %>
              <% end %>
             <%= paginate @posts %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render partial: "shared/following" %>

      </div>
    </div>
  </div>
  </section>
<% else %>
  <section>
    <div class="container">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading">How to Start?</div>
          <div class="panel-body">
            <p>Sign in using the bottom form</p>
            <p><b>OR</b></p>
            <p>Clicking in Sign up link to register</p>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Source code</div>
          <div class="panel-body">
            <p>You can view the source code in GitHub repository:</p>
            <p class="text-center">
              <a href="https://github.com/luisbilecki/social-network">Social-Network GitHub</a>
            </p>
            <p></p>
            <p></p>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>


<div id="edit-modal" class="modal fade" role="dialog"></div>